src/adapters/local-storage.ts
src/constants.ts
src/domain/index.ts
src/views/settings/settings.view.tsx

This PR implements an adapter to retrieve and store data from/to the local storage and implements the user-selected currency use case on the settings view.

Persist user selected currency

---

src/views/activity/activity.styles.ts
src/views/activity/components/transaction-card/transaction-card.styles.ts
src/views/confirmation/confirmation.styles.ts
src/views/home/components/amount-input/amount-input.styles.ts
src/views/home/components/header/header.styles.ts
src/views/home/components/list/list.styles.ts
src/views/home/components/transaction-form/transaction-form.styles.ts
src/views/home/home.styles.ts
src/views/login/login.styles.ts
src/views/settings/settings.styles.ts
src/views/shared/button/button.styles.ts
src/views/shared/card/card.styles.ts
src/views/shared/snackbar/snackbar.styles.ts
src/views/transaction-details/transaction-details.styles.ts

Change the dependency of borderRadius with `theme.spacing`
review them:

Change to number borderRadius

---

src/contexts/bridge.context.tsx
src/utils/fees.ts
src/views/transaction-details/transaction-details.view.tsx

This PR adds the historical fees information to the transaction details view.

Implement historical fees in transaction details

---

src/views/home/components/list/list.styles.ts
src/views/home/components/list/list.view.tsx
src/views/home/components/transaction-form/transaction-form.view.tsx
src/views/home/home.view.tsx

Closes #70 
When user initiate the form the chain selected will be the same that user've in Metamask and it's going to be synchronous to any change that the user do in Metamask and if the user change the from chain in the form, Metamask is going to request if can change to the clicked chain
review them:

Sync Metamask Network with chains in the form

---

src/adapters/error.ts
src/adapters/fiat-exchange-rates-api.ts
src/contexts/bridge.context.tsx
src/contexts/env.context.tsx
src/contexts/error.context.tsx
src/contexts/price-oracle.context.tsx
src/contexts/providers.context.tsx
src/views/activity/activity.view.tsx
src/views/app.view.tsx
src/views/home/components/transaction-form/transaction-form.view.tsx
src/views/transaction-confirmation/transaction-confirmation.view.tsx
src/views/transaction-details/transaction-details.view.tsx

Closes #50.
* Make sure that all the errors are properly caught
* Abstract the parsing and notifying of the errors
* Improve fiat-exchange-rates API error decoding
* Remove getTransactions from the bridge context

Make sure that all errors are properly caught

---

.github/workflows/push-docker-develop.yml

Fix wrong naming on workflow actions
Upload to develop and check that the docker image builds
review them:

Fix workflow, there were 2 actions with the same name

---

src/adapters/error.ts
src/views/login/login.view.tsx
src/views/shared/private-route/private-route.view.tsx

Closes #22 
This PR replaces the history routes that result from login and the initial redirection, so when the user clicks the browser's back button after having logged in, the browser goes back to the actual previous page.

Back buttons logic

---

src/views/activity/activity.styles.ts
src/views/activity/activity.view.tsx
src/views/activity/components/bridge-card/bridge-card.view.tsx
src/views/bridge-details/bridge-details.view.tsx
src/views/core/layout/layout.styles.ts
src/views/login/login.styles.ts
src/views/shared/page-loader/page-loader.styles.ts
src/views/shared/page-loader/page-loader.view.tsx
src/views/shared/spinner/spinner.styles.ts
src/views/shared/spinner/spinner.view.tsx

Closes #96.
This PR makes sure that all pages that require it show a spinner while the data is being fetched.

Fix or add the loading spinners as required

---

src/adapters/error.ts
src/adapters/storage.ts
src/utils/types.ts
src/views/bridge-confirmation/bridge-confirmation.view.tsx
src/views/home/components/token-list/token-list.view.tsx

Closes #99. 
This PR removes the type and parser for the error "MetaMask insufficient allowance", which was wrongly associated with the code `-32603`.
It also fixes a bug related to showing custom tokens from other networks.

Remove metamask insufficient allowance error and parser

---

src/views/home/components/bridge-form/bridge-form.view.tsx
src/views/home/components/chain-list/chain-list.styles.ts
src/views/home/components/chain-list/chain-list.view.tsx
src/views/home/components/token-list/token-list.styles.ts
src/views/home/components/token-list/token-list.view.tsx

Closes #119
This PR disables the custom token feature and improves a little bit the styles of the `TokenList` component.
review them:

Remove custom token feature

---

vite.config.ts

This PR disables React fast refresh in the vite config, as it's not working properly with React contexts as pointed out in https://github.com/vitejs/vite/issues/3301.
review them:

Disable React fast refresh

---

.env.example
.env.fetestnet
.env.integration
.env.internal-testnet
src/adapters/env.ts
src/domain/index.ts
src/views/settings/settings.view.tsx
src/vite-env.d.ts
vite.config.ts

Closes #139
This PR fixes the app version not showing on the settings view.

Fix the app version not showing on the settings view

---

.env.internal-testnet
.github/workflows/push-docker-develop.yml
.github/workflows/push-docker-main.yml

This PR updates the deployment information to be able to deploy to `Grapefruit` internal testnet.
review them:

Update deployment info

---

index.html
vite.config.ts

This PR adds the polyfill for the `global` nodejs builtin to be able to run the app in prod mode.
review them:

Fix global polyfill in prod mode

---

src/contexts/bridge.context.tsx
src/views/bridge-confirmation/bridge-confirmation.view.tsx

This PR temporary disables the gas estimation. This should be reverted ASAP.
review them:

Temporary disable gas estimation

---

src/views/activity/activity.styles.ts
src/views/activity/activity.view.tsx
src/views/activity/components/bridge-card/bridge-card.styles.ts
src/views/activity/components/bridge-card/bridge-card.view.tsx
src/views/bridge-confirmation/bridge-confirmation.view.tsx
src/views/bridge-details/bridge-details.view.tsx
src/views/login/login.styles.ts

Closes #146.
This PR disables the "Bridge" and "Claim" buttons" where needed. It also fixes some design issues.

Disable the bridge button when it is clicked

---

src/adapters/ethereum.ts
src/adapters/storage.ts
src/constants.ts
src/contexts/bridge.context.tsx
src/domain/index.ts
src/utils/labels.ts
src/utils/serializers.ts
src/views/activity/activity.view.tsx
src/views/activity/components/bridge-card/bridge-card.styles.ts
src/views/activity/components/bridge-card/bridge-card.view.tsx
src/views/bridge-confirmation/bridge-confirmation.view.tsx
src/views/bridge-details/bridge-details.view.tsx

This PR improves the L1 fee estimation. We need to increase it the estimated gas price in a 20% to be sure that successive bridge txs are successful. This will be added in the future for L2 as well (once the gas estimation works fast).
review them:

Improve L1 gas estimation

---

src/adapters/ethereum.ts
src/adapters/storage.ts
src/constants.ts
src/contexts/bridge.context.tsx
src/contexts/providers.context.tsx
src/domain/index.ts
src/utils/labels.ts
src/utils/serializers.ts
src/views/activity/activity.view.tsx
src/views/activity/components/bridge-card/bridge-card.styles.ts
src/views/activity/components/bridge-card/bridge-card.view.tsx
src/views/bridge-confirmation/bridge-confirmation.view.tsx
src/views/bridge-details/bridge-details.view.tsx

This PR sets the `nativeCurrency` of each chain to be able to set it up properly when adding the network to MetaMask. Currently it was being set to `unknown`.
review them:

Add nativeCurrency property to chain

---

package-lock.json
package.json
src/adapters/storage.ts
src/contexts/bridge.context.tsx
src/utils/serializers.ts
src/views/activity/activity.view.tsx
src/views/bridge-confirmation/bridge-confirmation.view.tsx

This PR addresses the comments that were left open in [this PR](https://github.com/0xPolygonHermez/zkevm-bridge-ui/pull/175)

Refactor pending tx parsing and local storage

---

vite.config.ts

This PR enbles the sourcemaps to the UI build.

Add sourcemaps

---

src/adapters/storage.ts
src/contexts/bridge.context.tsx
src/utils/labels.ts
src/utils/serializers.ts
src/views/login/login.view.tsx

We need to save in different list the pendingTx per account because maybe we can display pendingTxs from an account that it's not connected
review them:

Saved account info to filter pendingTx

---

src/views/home/components/amount-input/amount-input.view.tsx

Closes #198 
When the user clicks the MAX button in the form, the amount in the input takes into account the limitation imposed by the contract in `maxEtherBridge`.

Make the MAX button honor the limit imposed by maxEtherBridge

---

src/adapters/error.ts
src/contexts/providers.context.tsx
src/utils/types.ts
src/views/activity/activity.view.tsx
src/views/bridge-confirmation/bridge-confirmation.view.tsx
src/views/bridge-details/bridge-details.view.tsx
src/views/home/home.view.tsx
src/views/shared/network-box/network-box.styles.ts
src/views/shared/network-box/network-box.view.tsx
src/views/shared/network-selector/network-selector.view.tsx

This PR disables the MetaMask button in the `NetworkBox` component while it's requesting MetaMask to add the network.
review them:

Disable MetaMask button in the NetworkBox component

---

src/contexts/providers.context.tsx
src/views/activity/activity.view.tsx
src/views/bridge-confirmation/bridge-confirmation.view.tsx
src/views/home/home.view.tsx
src/views/login/login.styles.ts
src/views/login/login.view.tsx
src/views/shared/network-box/network-box.view.tsx

Closes #202 
This PR adds the network info box to the login screen.

Show the network info box in the login screen

---

src/constants.ts
src/views/shared/network-box/network-box.styles.ts
src/views/shared/network-box/network-box.view.tsx

This PR adds a "Report an issue" button to be able to open a ticket in the Polygon HelpDesk.
review them:

Add report an issue button to the NetworkBox component

---

src/adapters/ethereum.ts
src/constants.ts
src/contexts/bridge.context.tsx
src/contexts/providers.context.tsx
src/contexts/tokens.context.tsx
src/domain/index.ts
src/utils/feature-toggles.ts
src/utils/labels.ts
src/views/activity/activity.view.tsx
src/views/bridge-confirmation/bridge-confirmation.view.tsx
src/views/bridge-details/bridge-details.view.tsx
src/views/core/router/router.view.tsx
src/views/home/components/bridge-form/bridge-form.view.tsx
src/views/home/components/header/header.view.tsx
src/views/settings/settings.styles.ts
src/views/settings/settings.view.tsx
src/views/shared/network-box/network-box.view.tsx
src/views/shared/network-selector/network-selector.view.tsx
src/views/shared/private-route/private-route.view.tsx

Closes #144
This issue improves the application login process, automatically logging in (connecting the provider) when the MetaMask account is already connected to the dapp.
It also removes the logout button (which no longer makes sense, since it only disconnected the provider), and therefore, hides the Settings section when there are no data to show there.

Improve the login flow

---

src/contexts/bridge.context.tsx
src/contexts/providers.context.tsx
src/domain/index.ts
src/utils/addresses.ts
src/utils/serializers.ts
src/views/activity/components/bridge-card/bridge-card.view.tsx
src/views/bridge-confirmation/bridge-confirmation.view.tsx
src/views/bridge-details/bridge-details.view.tsx
src/views/home/components/bridge-form/bridge-form.view.tsx
src/views/login/login.view.tsx
src/views/shared/error-message/error-message.styles.ts
src/views/shared/error-message/error-message.view.tsx

This PR adds a check to the `BridgeDetails` page to check the current user has participated in a Bridge, wether as a sender or a receiver.
review them:

Check if the current connected account is allowed to see the details of a bridge
